EntregaProductoTerminado/Controllers/ProductoTerminadoController.cs
using System;
using EntregaProductoTerminado.Models;
using EntregaProductoTerminado.ViewModels;
using EntregaProductoTerminado.Repositories;
using System.Web.Mvc;
using EntregaProductoTerminado.Email;
using System.Net.Mail;

namespace EntregaProductoTerminado.Controllers
{
    public class ProductoTerminadoController : Controller
    {
        // GET: Productos Terminados
        [HttpGet]
        public ActionResult Entrega(string opnumber)
        {
            if (opnumber != null)
            {
                MetricsRepository metrics = new MetricsRepository();
                DiboRepository dibo = new DiboRepository();
                OrdenDeProduccionViewModel viewModel = new OrdenDeProduccionViewModel();
                try
                {
                    OrdenDeProduccion ordenDeProduccion = metrics.GetByOp(opnumber);
                    viewModel.transactionMessage = ordenDeProduccion == null ? 
                        "No existe una orden de producción con el valor "
                        + opnumber.ToString().Trim() : "";
                    viewModel.ordenDeProduccion = ordenDeProduccion ?? new OrdenDeProduccion();
                    viewModel.OPHistorial = dibo.Consult(opnumber);
                }
                catch (Exception e)
                {
                    viewModel.transactionMessage = "Se ha presentado un error en la búsqueda" +
                        " de la orden de producción, favor contactar a los administradores de la página";
                }
                finally
                {
                    metrics.Dispose();
                    dibo.Dispose();
                }
                return View(viewModel);
            }
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Entrega(OrdenDeProduccionViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                viewModel.ordenDeProduccion.FechaIngreso = DateTime.Now;
                DiboRepository dibo = new DiboRepository();
                OrdenDeProduccionViewModel ordenDeProduccionViewModel =
                    new OrdenDeProduccionViewModel();
                try
                {
                    if (viewModel != null 
                        && !String.IsNullOrEmpty(viewModel.ordenDeProduccion.NumeroOrdenProduccion))
                    {
                        //TODO in this part, change the insert in update should insert a new line por entrada a PT
                        if (dibo.Exists(viewModel.ordenDeProduccion.NumeroOrdenProduccion))
                        {
                            dibo.Update(viewModel.ordenDeProduccion);
                            ordenDeProduccionViewModel.transactionMessage = 
                                "Ingreso de entrega parcial exitosa, " +
                                "ha sido enviado un correo a los encargados" +
                                " de producto terminado";
                        }
                        else
                        {
                            viewModel.ordenDeProduccion.Entregas = 1;
                            if (viewModel.ordenDeProduccion.TotalCalculado > 
                                viewModel.ordenDeProduccion.MaximoAceptadoPorCliente)
                            {
                                viewModel.ordenDeProduccion.Excedente =
                                    viewModel.ordenDeProduccion.TotalCalculado - 
                                    viewModel.ordenDeProduccion.MaximoAceptadoPorCliente;
                            }
                            dibo.Add(viewModel.ordenDeProduccion);
                            ordenDeProduccionViewModel.transactionMessage = 
                                "Los valores han sido ingresados en el sistema de " +
                                "forma correcta, ha sido enviado un correo a los " + 
                                "encargados de producto terminado";
                        }
                        /*
                        PTSignal pT = new PTSignal("jchavarria@grupovargas.com, " +
                            "msanchez@grupovargas.com,focampo@grupovargas.com, " +
                            "dbarquero@grupovargas.com, mfonseca@grupovargas.com, " +
                            "cacuña@grupovargas.com, gvargas@grupovargas.com," +
                            "rrojas@grupovargas.com, fsanabria@grupovargas.com," +
                            "dramirez@grupovargas.com");
                        */
                        PTSignal pT = new PTSignal("lsanchez@grupovargas.com");
                        pT.SendEmail(viewModel.ordenDeProduccion);
                        dibo.Save();
                    }
                }
                catch (SmtpException exc)
                {
                    ordenDeProduccionViewModel.transactionMessage = 
                        "Ocurrió un error en el envío del correo a los encargados de " +
                        "producto terminado, favor contactar al administrador de la página";
                }
                catch (Exception e)
                {
                    ordenDeProduccionViewModel.transactionMessage = 
                        "Error en ingreso de datos al sistema, favor volver a intentar";
                }
                finally
                {
                    dibo.Dispose();
                }
                return View(ordenDeProduccionViewModel);
            }
            // In the return, lets send a message with the state of the transaction
            return View();
        }

        // GET: Historial
        [HttpGet]
        public ActionResult Historial(HistorialProductoTerminadoViewModel historialProducto)
        {
            if (ModelState.IsValid)
            {
                DiboRepository dibo = new DiboRepository();
                historialProducto.OPHistorial = dibo.OrdenList(historialProducto);
                dibo.Dispose();
                return View(historialProducto);
            }
            //En esta parte vamos a hacer la consulta a la tabla de OrdenDeProduccion
            return View();
        }
    }
}

EntregaProductoTerminado/Views/ProductoTerminado/entrega.cshtml
@model EntregaProductoTerminado.ViewModels.OrdenDeProduccionViewModel
@{
    ViewBag.Title = "Entrega";
}

<h2>Ingreso de Material a Bodega</h2>

@using (Html.BeginForm("Entrega", "ProductoTerminado", FormMethod.Get))
{
<div class="form-inline">
    <label for="opnumber" id="title">Orden de Producción</label>
    <input autocomplete="on" id="opnumber" class="form-control" type="text" name="opnumber" placeholder="# de OP" />
    <input class="btn btn-primary" type="submit" value="Buscar" />
</div>
}
<p>@Html.DisplayFor(model => model.transactionMessage)</p>
<hr />
@using (Html.BeginForm("Entrega", "ProductoTerminado", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.HiddenFor(model => model.ordenDeProduccion.Entregas)
    @Html.AntiForgeryToken()
    <ul class="result">
        <li class="border-colored">
            <span>@Html.DisplayNameFor(model => model.ordenDeProduccion.NumeroOrdenProduccion) : </span>
            @Html.DisplayFor(model => model.ordenDeProduccion.NumeroOrdenProduccion)
        </li>
        @Html.HiddenFor(model => model.ordenDeProduccion.NumeroOrdenProduccion)

        <li class="border-colored">
            <span>@Html.DisplayNameFor(model => model.ordenDeProduccion.Cliente) : </span>
            @Html.DisplayFor(model => model.ordenDeProduccion.Cliente)
        </li>
        @Html.HiddenFor(model => model.ordenDeProduccion.Cliente)

        <li class="border-colored">
            <span>@Html.DisplayNameFor(model => model.ordenDeProduccion.OrdenDeCompra) : </span>
            @Html.DisplayFor(model => model.ordenDeProduccion.OrdenDeCompra)
        </li>
        @Html.HiddenFor(model => model.ordenDeProduccion.OrdenDeCompra)

        <li class="border-colored">
            <span>@Html.DisplayNameFor(model => model.ordenDeProduccion.CodProductoInterno) : </span>
            @Html.DisplayFor(model => model.ordenDeProduccion.CodProductoInterno)
        </li>
        @Html.HiddenFor(model => model.ordenDeProduccion.CodProductoInterno)

        <li class="border-colored">
            <span>@Html.DisplayNameFor(model => model.ordenDeProduccion.PorcentajeTolerancia) : </span>
            @Html.DisplayFor(model => model.ordenDeProduccion.PorcentajeTolerancia)%
        </li>
        @Html.HiddenFor(model => model.ordenDeProduccion.PorcentajeTolerancia)

        <li class="border-colored">
            <span>@Html.DisplayNameFor(model => model.ordenDeProduccion.Excedente) : </span>
            @Html.DisplayFor(model => model.ordenDeProduccion.Excedente)
        </li>
        @Html.HiddenFor(model => model.ordenDeProduccion.Excedente)

        <li class="border-colored">
            <span>@Html.DisplayNameFor(model => model.ordenDeProduccion.MaximoAceptadoPorCliente) : </span>
            @Html.DisplayFor(model => model.ordenDeProduccion.MaximoAceptadoPorCliente)
        </li>
        @Html.HiddenFor(model => model.ordenDeProduccion.MaximoAceptadoPorCliente)

        <li class="border-colored">
            <span>@Html.DisplayNameFor(model => model.ordenDeProduccion.TotalEnSistema) : </span>
            @Html.DisplayFor(model => model.ordenDeProduccion.TotalEnSistema)
        </li>
        @Html.HiddenFor(model => model.ordenDeProduccion.TotalEnSistema)
    </ul>
    <fieldset>
        <div class="form-group">
            <div class="col col-md-4">
                <label for="ordenDeProduccion_Bultos">@Html.DisplayNameFor(model => model.ordenDeProduccion.Bultos)
                (@Html.DisplayFor(model => model.ordenDeProduccion.Bultos))</label> <!--User Input-->
                @Html.TextBoxFor(model => model.ordenDeProduccion.Bultos, new { @class = "form-control", @autocomplete = "off",
                @oninput = "thousandSeparator('ordenDeProduccion_Bultos')", @Value = '0'})
                @Html.ValidationMessageFor(model => model.ordenDeProduccion.Bultos, "",new { @class = "text-danger" })
            </div>
            <div class="col col-md-4">
                <label for="ordenDeProduccion_UnidadesPorBulto">@Html.DisplayNameFor(model => model.ordenDeProduccion.UnidadesPorBulto)</label> <!--User Input-->
                @Html.TextBoxFor(model => model.ordenDeProduccion.UnidadesPorBulto, new { @class = "form-control", @autocomplete = "off",
                @oninput = "thousandSeparator('ordenDeProduccion_UnidadesPorBulto')", @Value = '0'})
                @Html.ValidationMessageFor(model => model.ordenDeProduccion.UnidadesPorBulto, "", new { @class = "text-danger" })
            </div>
            <div class="col col-md-4">
                <label for="orderDeProduccion_Fraccion">@Html.DisplayNameFor(model => model.ordenDeProduccion.Fraccion) 
                (@Html.DisplayFor(model => model.ordenDeProduccion.Fraccion))</label> <!--User Input-->
                @Html.TextBoxFor(model => model.ordenDeProduccion.Fraccion, new { @class = "form-control", @autocomplete = "off",
                @oninput = "thousandSeparator('ordenDeProduccion_Fraccion')", @Value = '0'})
                @Html.ValidationMessageFor(model => model.ordenDeProduccion.Fraccion, "", new { @class = "text-danger" })
            </div>
        </div>
        <div>
            <label for="orderDeProduccion_TotalCalculado">@Html.DisplayNameFor(model => model.ordenDeProduccion.TotalCalculado)
                (@Html.DisplayFor(model => model.ordenDeProduccion.TotalCalculado))</label> <!--This value is calculate-->
            @Html.TextBoxFor(model => model.ordenDeProduccion.TotalCalculado, new { @class = "form-control", @readonly = "readonly",
           @oninput = "thousandSeparator('ordenDeProduccion_TotalCalculado')", @Value = '0' })
            @Html.HiddenFor(model => model.ordenDeProduccion.TotalCalculado, new { @id="totalCalculado_Hidden" })
        </div>
        <div class="form-group">
            <div class="col col-lg-6">
                <button id="big-blue-button" type="button" data-toggle="modal"
                        data-target="#request-modal" onclick="IfSend()">
                    Ingresar a Bodega
                </button>
            </div>
        </div>

        <div class="modal fade" id="request-modal" tabindex="-1" role="alertdialog" aria-labelledby="request-modal-label">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button id="close-button" type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="request-modal-label">¿Desea guardar la entrada?</h4>
                    </div>
                    <div class="modal-body">
                        <p id="SubmitMessage">
                            <!--Acá mostrar el mensaje de guardado o si se pasa de valor-->
                            El proceso de guardado enviará un correo a los responsables de producto terminado, además
                            de guardar la información del lote.
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button id="cancel-button" type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                        <button id="save_button" type="submit" class="btn btn-danger" data-loading-text="Guardando..."
                                autocomplete="off">
                            Guardar
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
    <section class="table-responsive">
        <h4>Entregas anteriores</h4>
        <table>
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(model => model.ordenDeProduccion.Entregas)</th>
                    <th>@Html.DisplayNameFor(model => model.ordenDeProduccion.Bultos)</th>
                    <th>@Html.DisplayNameFor(model => model.ordenDeProduccion.UnidadesPorBulto)</th>
                    <th>@Html.DisplayNameFor(model => model.ordenDeProduccion.Fraccion)</th>
                    <th>@Html.DisplayNameFor(model => model.ordenDeProduccion.TotalCalculado)</th>
                    <th>@Html.DisplayNameFor(model => model.ordenDeProduccion.TotalEnSistema)</th>
                    <th>@Html.DisplayNameFor(model => model.ordenDeProduccion.PorcentajeTolerancia)</th>
                    <th>@Html.DisplayNameFor(model => model.ordenDeProduccion.FechaIngreso)</th>
                    <th>@Html.DisplayNameFor(model => model.ordenDeProduccion.Excedente)</th>
                    <th>@Html.DisplayNameFor(model => model.ordenDeProduccion.MaximoAceptadoPorCliente)</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    if (Model.OPHistorial != null)
                    {
                        for (int i = 0; i < Model.OPHistorial.Count; i++)
                        {
                            <tr class="row-highlight">
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].Entregas)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].Bultos)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].UnidadesPorBulto)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].Fraccion)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].TotalCalculado)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].TotalEnSistema)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].PorcentajeTolerancia)%</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].FechaIngreso)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].Excedente)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].MaximoAceptadoPorCliente)</td>
                            </tr>
                        }
                    }
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="10">Fin de la lista</td>
                </tr>
            </tfoot>
        </table>
    </section>
    
}

<br />
@section Scripts{
 @Scripts.Render("~/bundles/jqueryval")

 }

EntregaProductoTerminado/Views/ProductoTerminado/historial.cshtml
@model EntregaProductoTerminado.ViewModels.HistorialProductoTerminadoViewModel
@{
    ViewBag.Title = "historial";
}
                                                                                

<!--Primero usar html semantics para dividir las partes que consisten la página-->
<!--Luego agregar cada elemento de html necesario-->
<section>
    <!--Search section-->
    <h2>Historial de ingresos</h2>
    @using (Html.BeginForm("Historial", "ProductoTerminado", FormMethod.Get))
    {
    <div class="form-group">
        <label for="historialInput">Buscar por</label>
        @Html.TextBoxFor(model => model.historialInput, new { @class = "form-control", 
        @placeholder = "OP o Cliente" })
    </div>
    <div class="form-inline">
        @Html.DisplayNameFor(model => model.fechaInicio)
        @Html.TextBoxFor(model => model.fechaInicio, new { Value = DateTime.Today.ToString("yyyy-MM-dd"),
        @class = "form-control datepicker", @readonly = "readonly" })
        @Html.DisplayNameFor(model => model.fechaFin)
        @Html.TextBoxFor(model => model.fechaFin, new { Value = DateTime.Today.ToString("yyyy-MM-dd"),
        @class = "form-control datepicker", @readonly = "readonly" })
        <input class="btn btn-primary" type="submit" value="Buscar" />
    </div>
     
    }
</section>

<section class="table-responsive">
    <h4 >Resultado de la búsqueda</h4>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>@Html.DisplayNameFor(model => model.OrdenDeProduccion.Entregas)</th>
                    <th>@Html.DisplayNameFor(model => model.OrdenDeProduccion.NumeroOrdenProduccion)</th>
                    <th>@Html.DisplayNameFor(model => model.OrdenDeProduccion.Cliente)</th>
                    <th>@Html.DisplayNameFor(model => model.OrdenDeProduccion.Bultos)</th>
                    <th>@Html.DisplayNameFor(model => model.OrdenDeProduccion.UnidadesPorBulto)</th>
                    <th>@Html.DisplayNameFor(model => model.OrdenDeProduccion.Fraccion)</th>
                    <th>@Html.DisplayNameFor(model => model.OrdenDeProduccion.TotalCalculado)</th>
                    <th>@Html.DisplayNameFor(model => model.OrdenDeProduccion.TotalEnSistema)</th>
                    <th>@Html.DisplayNameFor(model => model.OrdenDeProduccion.PorcentajeTolerancia)</th>
                    <th>@Html.DisplayNameFor(model => model.OrdenDeProduccion.FechaIngreso)</th>
                    <th>@Html.DisplayNameFor(model => model.OrdenDeProduccion.Excedente)</th>
                    <th>@Html.DisplayNameFor(model => model.OrdenDeProduccion.MaximoAceptadoPorCliente)</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    if (Model.OPHistorial != null)
                    {
                        for (int i = 0; i < Model.OPHistorial.Count; i++)
                        {
                            <tr class="row-highlight">
                                <td scope="row">@(i + 1)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].Entregas)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].NumeroOrdenProduccion)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].Cliente)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].Bultos)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].UnidadesPorBulto)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].Fraccion)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].TotalCalculado)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].TotalEnSistema)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].PorcentajeTolerancia)%</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].FechaIngreso)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].Excedente)</td>
                                <td>@Html.DisplayFor(model => model.OPHistorial[i].MaximoAceptadoPorCliente)</td>
                            </tr>
                        }
                    }
                }
            </tbody>
            <tfoot>
                <tr>
                    <td id="list-end" colspan="13">Fin de la lista</td>
                </tr>
            </tfoot>
        </table>
</section>